services:
  default:
    image: rufimelo/sandbox-reviewer:v1
    platform: linux/amd64
    command: "tail -f /dev/null"
    init: true
    stop_grace_period: 1s
    extra_hosts:
      - "gitea:host-gateway"
